// <auto-generated />
using System;
using CESIZen.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CESIZen.Shared.Models.Article", b =>
                {
                    b.Property<int>("id_article")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_article"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("createdById")
                        .HasColumnType("int");

                    b.Property<int>("id_category")
                        .HasColumnType("int");

                    b.Property<string>("imageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("lastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("id_article");

                    b.HasIndex("createdById");

                    b.HasIndex("id_category");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.Category", b =>
                {
                    b.Property<int>("id_category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_category"));

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_category");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.Menu", b =>
                {
                    b.Property<string>("id_menu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("id_page_stock")
                        .HasColumnType("int");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("sort_order")
                        .HasColumnType("int");

                    b.HasKey("id_menu");

                    b.HasIndex("id_page_stock");

                    b.HasIndex("label")
                        .IsUnique();

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.MoodDetail", b =>
                {
                    b.Property<int>("id_mood_detail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_mood_detail"));

                    b.Property<int>("id_mood_primary")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_mood_detail");

                    b.HasIndex("id_mood_primary");

                    b.ToTable("MoodDetails");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.MoodPrimary", b =>
                {
                    b.Property<int>("id_mood_primary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_mood_primary"));

                    b.Property<string>("titre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_mood_primary");

                    b.ToTable("MoodPrimaries");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.PageStock", b =>
                {
                    b.Property<int>("id_page_stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_page_stock"));

                    b.Property<string>("html_content")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_system_page")
                        .HasColumnType("bit");

                    b.Property<string>("slug_url")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id_page_stock");

                    b.ToTable("PageStocks");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.Profile", b =>
                {
                    b.Property<int>("id_profile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_profile"));

                    b.Property<string>("avatar")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("gender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("id_user")
                        .HasColumnType("int");

                    b.Property<DateTime?>("last_connection")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_profile");

                    b.HasIndex("id_user")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.Role", b =>
                {
                    b.Property<int>("id_role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_role"));

                    b.Property<string>("description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id_role");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.Session", b =>
                {
                    b.Property<int>("id_session")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_session"));

                    b.Property<string>("adress_ip")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("date_")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("expire_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_user")
                        .HasColumnType("int");

                    b.Property<string>("token")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id_session");

                    b.HasIndex("id_user");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.TrackerLog", b =>
                {
                    b.Property<int>("id_tracker_log")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_tracker_log"));

                    b.Property<string>("comment")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("date_")
                        .HasColumnType("datetime2");

                    b.Property<int>("id_mood_detail")
                        .HasColumnType("int");

                    b.Property<int>("id_profile")
                        .HasColumnType("int");

                    b.HasKey("id_tracker_log");

                    b.HasIndex("id_mood_detail");

                    b.HasIndex("id_profile");

                    b.ToTable("TrackerLogs");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.Property<int>("id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_user"));

                    b.Property<DateTime?>("birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("firstname")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("id_role")
                        .HasColumnType("int");

                    b.Property<string>("lastname")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("statut")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("id_user");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("id_role");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.Article", b =>
                {
                    b.HasOne("Shared.Models.User", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("createdById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CESIZen.Shared.Models.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("id_category")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.Menu", b =>
                {
                    b.HasOne("CESIZen.Shared.Models.PageStock", "PageStock")
                        .WithMany("Menus")
                        .HasForeignKey("id_page_stock")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PageStock");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.MoodDetail", b =>
                {
                    b.HasOne("CESIZen.Shared.Models.MoodPrimary", "MoodPrimary")
                        .WithMany("MoodDetails")
                        .HasForeignKey("id_mood_primary")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoodPrimary");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.Profile", b =>
                {
                    b.HasOne("Shared.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("CESIZen.Shared.Models.Profile", "id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.Session", b =>
                {
                    b.HasOne("Shared.Models.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("id_user")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.TrackerLog", b =>
                {
                    b.HasOne("CESIZen.Shared.Models.MoodDetail", "MoodDetail")
                        .WithMany("TrackerLogs")
                        .HasForeignKey("id_mood_detail")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CESIZen.Shared.Models.Profile", "Profile")
                        .WithMany("TrackerLogs")
                        .HasForeignKey("id_profile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MoodDetail");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.HasOne("CESIZen.Shared.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("id_role")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.MoodDetail", b =>
                {
                    b.Navigation("TrackerLogs");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.MoodPrimary", b =>
                {
                    b.Navigation("MoodDetails");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.PageStock", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.Profile", b =>
                {
                    b.Navigation("TrackerLogs");
                });

            modelBuilder.Entity("CESIZen.Shared.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Shared.Models.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Profile");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
